name: BritneySpears
favicon: null
layout_spectrum: 0.34334
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#97a6ab'
    - '#56666e'
    - '#181913'
    - '#454b49'
    - '#fae29d'
  brandStrength: 0.5
  lightness: 0.0625
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
