name: BritneySpears
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2863681854214519
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#97a6ab'
    - '#56666e'
    - '#181913'
    - '#454b49'
    - '#fae29d'
  brandStrength: 0.5
  lightness: 0.6957292098086327
  saturation: 0.6558323525823653
  rhythmicContrast: 0.9855552790686488
purpose: []
